IMS/Controllers/FrontendController.cs
using IMS.Service.Inteface;
using IMS.Service.Models;
using IMS.Service.Service;
using IMS.Service.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS.Controllers
{
    public class FrontendController : Controller
    {
        private ICategoryService category;

        private IKharidAdesService kharidAdesObj = null;
        private IProductService productObj;
        private IKharidTypeService kharidTypeObj;
        private IKharidAdesDetailsService kharidDetailsObj;
        private ICategoryService categoryObj;
        private IProductDetailsService productDetailsObj;
        private IGoods_exp_type samanBargaObj;
        private ISellerService sellerObj;
        private IOfficeService officeObj;
        private IKarmachariDetailsService karmachariDetailsObj;
        private IMagfaramService magFaramObj;
       
       
        private IUnitService unitObj;

        public FrontendController()
        {
            this.category = new CategoryService();
            productObj = new ProductService();
            kharidAdesObj = new KharidAdesService();
            kharidTypeObj = new KharidTypeService();
            kharidDetailsObj = new KharidAdesDetailsService();
            categoryObj = new CategoryService();
            productDetailsObj = new ProductDetailsService();
            sellerObj = new SellerService();
            officeObj = new OfficeService();
            karmachariDetailsObj = new KarmachariDetailsService();
            magFaramObj = new MagfaramService();
            unitObj = new UnitService();
            samanBargaObj = new GoodExpTypeService();

        }
        // GET: Frontend
        public ActionResult Index()
        {
          
            OfficeModel OfficeName;
           
            if (Session["id"]!= null)
            {

               OfficeName =  officeObj.GetOfficeByUser(Convert.ToInt32(Session["id"].ToString()));
                Session["Office_Id"] = OfficeName.Id;
                Session["ProjectName"] = OfficeName.ProjectName;
                Session["OfficeNameNep"] = OfficeName.NameNepali;
                Session["local_level_code"] = OfficeName.LocalLevelCode;
                ViewBag.officename = OfficeName.NameNepali;
                return View("~/Views/Frontend/Index.cshtml");
            }
            return RedirectToAction("Index", "Account");

        }
       
        [HttpPost]
        public ActionResult KharidAdesh(FormCollection collection)
        {
            CategoryModel category1 = new CategoryModel();
            category1.Category_name = collection["email"];
           
            category1.Parent_id = 0;
            int letc = category.Insert(category1);

            return View();
        }

        public ActionResult KhadridAdesAddView()
        {
            if (Session["Office_Id"] != null)
            {

                KharidAdeshViewModel Record = new KharidAdeshViewModel();
                KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
                KharidAdesDetailsModel kharidAdeshDetailsModel = new KharidAdesDetailsModel();
                Record.KharidAdeshModel = kharidAdeshModel;
                Record.KharidAdesDetailsModel = kharidAdeshDetailsModel;
                Record.KharidAdeshModel.KharidAdesNumber = kharidAdesObj.getKharidAdeshNumberByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
                Record.CategoryList = categoryObj.GetCategorySelectListItem();
                //Record.ProductList = productObj.GetProductSelectListItem();
                Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
                Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();
                return PartialView("~/Views/Shared/Frontend/KharidAdes/_add.cshtml", Record);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }
/// <summary>
///
/// </summary>
/// <returns></returns>
        public ActionResult KharidAdshEditView()
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            if (Session["Office_Id"] != null)
            {
                List<KharidAdeshModel> kharidAdeshModel = new List<KharidAdeshModel>();
                kharidAdeshModel = kharidAdesObj.getAllKharidAdeshByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
                return PartialView("~/Views/Frontend/_kharidAdshEditView.cshtml", kharidAdeshModel);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }

        public ActionResult KharidAdeshEditViewPage(int id)
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
            KharidAdesDetailsModel KharidAdesDetailsModel = new KharidAdesDetailsModel();
            //Record.KharidAdeshModel = kharidAdeshModel;
            Record.KharidAdesDetailsModel = KharidAdesDetailsModel;
            Record.KharidAdesDetailsModel.kharidAdeshModelList = kharidDetailsObj.getKharidAdeshDetailsByKharidAdeshIdAndOfficeId(id, Convert.ToInt32(Session["Office_Id"].ToString()));

            Session["kharidAdeshId"] = id;

            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            Record.ProductList = productObj.GetProductSelectListItem();
            Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
            Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();
            return PartialView("~/Views/Shared/Frontend/KharidAdes/_kharidAdeshEditPage.cshtml", Record);
        }

        public ActionResult DakhilaAddView()
        {
            DakhilaKharidAdeshViewModel Record = new DakhilaKharidAdeshViewModel();
            DakhilaModel dakhilaModel = new DakhilaModel();
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            if (Session["id"] != null )
            {

                Record.KharidAdeshList = kharidAdesObj.GetKharidListItemsByOfficId(Convert.ToInt32(Session["id"].ToString()));
                //Record.KharidAdeshDetailsList = kharidDetailsObj.GetKharidAdesDetailsList();
                Record.ProductList = productObj.GetProductSelectListItem();
                Record.sellerModelList = sellerObj.GetSellerByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            }
            return PartialView("~/Views/Shared/Frontend/Dakhila/_dakhilaAdd.cshtml",Record);
        }

        public ActionResult MagFaram()
        {

            MagFaramViewModel Record = new MagFaramViewModel();
            MagfaramModel MagfaramModel = new MagfaramModel();
            Record.MagfaramModel = MagfaramModel;
            Record.MagfaramModel.Mag_faram_number = magFaramObj.getMaxMagFaramNumberByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            Record.KarmachariDetailsModel = karmachariDetailsObj.GetKarmachariByOfficeId((Session["Office_Id"].ToString()));
            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            
            Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
            Record.ProductList = productObj.GetProductSelectListItem();
            return PartialView("~/Views/Shared/Frontend/MagFaram/_magFaram.cshtml", Record);
        }

        public ActionResult Nikasa()
        {
            NikasaMagFaramViewModel Record = new NikasaMagFaramViewModel();
            Record.MagFaramList = magFaramObj.GetMagFaramIdByOfficeId(Convert.ToInt32(Session["id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/Nikasa/_nikasaAddView.cshtml",Record);
        }

        public ActionResult KharidAdeshReportView()
        {
            
            KharidAdesDetailsModel Record = new KharidAdesDetailsModel();
            Record.KharidAdeshListItem = kharidAdesObj.GetKharidListItemsByOfficId(Convert.ToInt32(Session["id"].ToString()));
           
            return PartialView("~/Views/Shared/Frontend/KharidAdes/_kharidAdeshReport.cshtml", Record);
        }

       public ActionResult MagFaramReportView()
        {
            MagFaramDetailsModel Record = new MagFaramDetailsModel();
            Record.MagFaramList = magFaramObj.GetMagFaramIdByOfficeId(Convert.ToInt32(Session["id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/MagFaram/_magFaramReport.cshtml", Record);
        }

        public ActionResult KarmachariView()
        {

            return PartialView("~/Views/Shared/Frontend/Karmachari/_karmachari.cshtml");

        }

        public ActionResult SellerView()
        {

            return PartialView("~/Views/Shared/Frontend/Seller/_seller.cshtml");
        }

        public ActionResult FormAuthorityView()
        {
            FormAuthorityModel Record = new FormAuthorityModel();
             Record.KarmachariList = karmachariDetailsObj.getKarmachariDetailsByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/FormAuthority/_formAuthority.cshtml", Record);
        }

        public ActionResult ProductAddView()
        {
            ProductViewModel Record = new ProductViewModel();
            Record.ProductList = productObj.GetAll();
            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            Record.UnitList = unitObj.UnitSelectItem();
            Record.SamanBargaList = samanBargaObj.GetSamanBargaList();
            return PartialView("~/Views/Shared/Frontend/Product/_productAddView.cshtml", Record);
        }

        public ActionResult ProductDetailsAddView()
        {
            ProductDetailsModel Record = new ProductDetailsModel();

IMS/Controllers/MagFaramDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.Service.Models;
using IMS.Service.Inteface;
using IMS.Service.Service;

namespace IMS.Controllers
{
    public class MagFaramDetailsController : Controller
    {
        // GET: MagFaramDetails
        private IMagFaramDetailsService magFaramDetailsObj;
        public MagFaramDetailsController()
        {
            this.magFaramDetailsObj = new MagFaramDetailsService();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MagFaramReportView(MagFaramDetailsModel md)
        {
            int mag_faram_id = md.Mag_Faram_Id;
            List<MagFaramDetailsModel> data = magFaramDetailsObj.GetMagFaramDetailsByMagFaramId(mag_faram_id);

            return View();
        }
    }
}

IMS/Controllers/MagfaramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.Service.Models;
using IMS.Service.Inteface;
using IMS.Service.Service;

namespace IMS.Controllers
{
    public class MagfaramController : Controller
    {
        // GET: Magfaram

        private IMagfaramService magfaramObj;
        private IMagFaramDetailsService magFaramDetailsObj;
        public MagfaramController()
        {
            this.magfaramObj = new MagfaramService();
            this.magFaramDetailsObj = new MagFaramDetailsService();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MagfaramModel mm)
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(MagfaramModel mm)
        {
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
        }


        // Save Mag Faramand and MagFaram Details From Mag faram View
        public JsonResult SaveFromFront(MagfaramModel magFaram, MagFaramDetailsModel[] magFaramDetails)
        {
           int temp = magfaramObj.Insert(magFaram);
            foreach (var item in magFaramDetails)
            {
                item.Mag_Faram_Id = temp;

                magFaramDetailsObj.Insert(item);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        // Fetch Mag Faram Id Called from Nikasa View

        public JsonResult GetMagFaramById(int id)
        {
            List<MagFaramDetailsModel> data = magFaramDetailsObj.GetMagFaramByMagFaramId(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

      
    }
}

IMS/Views/Shared/Frontend/MagFaram/_magFaram.cshtml
@model IMS.Service.ViewModels.MagFaramViewModel
<div class="content-cantainer">
    <div class="opend-file-wrapper">
        <span class="file-icon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
        <span class="opened-file-name">माग फारम</span>
    </div>
    <div class="content-field">
        <form class="form-horizontal" id="magFaram" method="post" action="@Url.Action("Create", "#")">
            <div class="form-group">
                @Html.LabelFor(model => model.MagfaramModel.Mag_faram_number, "माग न.", htmlAttributes: new { @class = "control-label form-label" })

                @Html.EditorFor(model => model.MagfaramModel.Mag_faram_number, new { htmlAttributes = new { disabled = "disabled", @class = "form-field" } })
                @Html.ValidationMessageFor(model => model.MagfaramModel.Mag_faram_number, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MagFaramDetailsModel.Request_By, "माग गर्ने", htmlAttributes: new { @class = "control-label form-label" })
                @Html.DropDownListFor(model => model.MagFaramDetailsModel.Request_By, Model.KarmachariDetailsModel, "--माग गर्ने छान्नुहोस--", htmlAttributes: new { @class = "form-field" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MagFaramDetailsModel.Category_Id, "क्याटेगोरी", htmlAttributes: new { @class = "control-label form-label" })
                @Html.DropDownListFor(model => model.MagFaramDetailsModel.Category_Id, Model.CategoryList, "---------", htmlAttributes: new { @class = "form-field" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MagFaramDetailsModel.Product_Id, "प्रोडक्ट", htmlAttributes: new { @class = "control-label form-label" })
                @Html.DropDownListFor(model => model.ProductModel.Id, new SelectList(" "), "----------", new { @class = "form-field" })

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ProductDetailsModel.Id, "प्रोडक्ट डिटेल्स", htmlAttributes: new { @class = "control-label form-label" })
                @Html.DropDownListFor(model => model.ProductDetailsModel.Id, new SelectList(" "), "----------", new { @class = "form-field" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MagFaramDetailsModel.Quantity, "क्वानटिटी", htmlAttributes: new { @class = "control-label form-label" })

                @Html.EditorFor(model => model.MagFaramDetailsModel.Quantity, new { htmlAttributes = new { @class = "form-field" } })
                @Html.ValidationMessageFor(model => model.MagFaramDetailsModel.Quantity, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                <label>मिति</label>
                <input type="text" class="nep_date form-control form-field" id="nepali_date" name="KharidAdeshModel.Created_date" />


            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="button" id="kharid_ades_form_btn" onclick="MagFaramformSubmit(event)" class="btn btn-default">थप</button>
                </div>
            </div>
        </form>
    </div>
    <div class="display-content">
        <table class="table table-bordered " id="mag_faram_table">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>पेश गर्ने</th>
                    <th>क्याटोगोरी</th>
                    <th>प्रोडक्ट</th>
                    <th>प्रोडक्ट डिटेल्स</th>
                    <th>सङ्ख्या</th>
                </tr>
            </thead>
            <tbody>
                <tr></tr>

            </tbody>
        </table>
        <input type="hidden" value="@Session["id"]" id="myHiddenVar" />
        <input type="hidden" value="@Session["Office_Id"]" id="officeId" />
        <div class="submit-buttonss btn-group">
            <button class="btn btn-primary" id="save" onclick="saveMagFaramDetails()" type="button"> Save </button>
            <button class="btn btn-warning" type="button"> Clear </button>
        </div>
    </div>
</div>

<script>
var MyAppUrlSettings = {
    MagFaramURL : '@Url.Action("SaveFromFront","Magfaram")'  // ("Function", "Controller")
}
</script>

<script>
    $('.nep_date').nepaliDatePicker({
        dateFormat: "%y-%m-%d"
    });
    var d = new Date();
    var month = d.getMonth() + 1;
    var day = d.getDate();
    var year = d.getFullYear();
    var nepDate = calendarFunctions.getBsDateByAdDate(year, month, day);
    // console.log(calendarFunctions.getBsDateByAdDate(year, month, day));
    $('#nepali_date').val(calendarFunctions.getNepaliNumber(nepDate.bsYear) + '-' + calendarFunctions.getNepaliNumber(nepDate.bsMonth) + '-' + calendarFunctions.getNepaliNumber(nepDate.bsDate));
</script>

<script>
    $(document).ready(function () {
        $('#MagFaramDetailsModel_Category_Id').change(function () {
            var category_id = $(this).val();
            var office_id = $('#officeId').val();
            //alert('hunter');
            //console.log(category_id);
            //console.log(office_id);
            $.ajax({

                url: "/Product/GetProductByCategoryIdOfficeId/",
                data: {
                    category_id: category_id,
                    office_id: office_id
                },
                type: 'Get',
                contentType: "json",
                dataType: "json",
                success: function (result) {
                    $("#ProductModel_Id").html(' '); //khali gareko

                    $("#ProductModel_Id").append("<option>---------</option>")

                    $.each(result, function (key, value) {
                       // console.log(value);
                        $("#ProductModel_Id").append("<option value='" + value.Id + "'>" + value.Product_name + "</option>")
                    })
                }

            })
        });

    });

</script>

<script>
    $(document).ready(function () {
        $('#ProductModel_Id').change(function () {
            var product_id = $('#ProductModel_Id').val();
            var office_id = $('#officeId').val();
            //alert('hunter');
            $.ajax({
                url: "/ProductDetails/getProductDetailsByProductId/",
                data: {
                    product_id: product_id,
                    office_id: office_id
                },

                type: 'Get',
                contentType: JSON,
                success: function (result) {

                    $("#ProductDetailsModel_Id").html(' ');
                    $("#ProductDetailsModel_Id").append("<option>-------- </option>")

                    $.each(result, function (key, value) {
                        //console.log(value);
                        $("#ProductDetailsModel_Id").append("<option value='" + value.Id + "'>" + value.Specification_Name + "</option>")
                    })
                }
            })
        });

    });
</script>

IMS/Views/Shared/Frontend/MagFaram/_magFaramReport.cshtml
@model IMS.Service.Models.MagFaramDetailsModel

@using (Html.BeginForm("MagFaramReportView", "MagFaramDetails", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Khrid Adesh Report</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="miti">आर्थिक वर्ष</label>
            <select>

                <option>2075/76</option>
            </select>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                @Html.LabelFor(model => model.Mag_Faram_Id, "माग फारम न.", htmlAttributes: new { @class = "control-label form-label " })

                @Html.DropDownListFor(model => model.Mag_Faram_Id, Model.MagFaramList, htmlAttributes: new { @class = "form-field  " })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" formtarget="_blank" value="हेर्ने" class="btn btn-default" />
            </div>
        </div>
    </div>
}