IMS/Controllers/FrontendController.cs
using IMS.Service.Inteface;
using IMS.Service.Models;
using IMS.Service.Service;
using IMS.Service.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS.Controllers
{
    public class FrontendController : Controller
    {
        private ICategoryService category;

        private IKharidAdesService kharidAdesObj = null;
        private IProductService productObj;
        private IKharidTypeService kharidTypeObj;
        private IKharidAdesDetailsService kharidDetailsObj;
        private ICategoryService categoryObj;
        private IProductDetailsService productDetailsObj;
        private IGoods_exp_type samanBargaObj;
        private ISellerService sellerObj;
        private IOfficeService officeObj;
        private IKarmachariDetailsService karmachariDetailsObj;
        private IMagfaramService magFaramObj;
       
       
        private IUnitService unitObj;

        public FrontendController()
        {
            this.category = new CategoryService();
            productObj = new ProductService();
            kharidAdesObj = new KharidAdesService();
            kharidTypeObj = new KharidTypeService();
            kharidDetailsObj = new KharidAdesDetailsService();
            categoryObj = new CategoryService();
            productDetailsObj = new ProductDetailsService();
            sellerObj = new SellerService();
            officeObj = new OfficeService();
            karmachariDetailsObj = new KarmachariDetailsService();
            magFaramObj = new MagfaramService();
            unitObj = new UnitService();
            samanBargaObj = new GoodExpTypeService();

        }
        // GET: Frontend
        public ActionResult Index()
        {
          
            OfficeModel OfficeName;
           
            if (Session["id"]!= null)
            {

               OfficeName =  officeObj.GetOfficeByUser(Convert.ToInt32(Session["id"].ToString()));
                Session["Office_Id"] = OfficeName.Id;
                Session["ProjectName"] = OfficeName.ProjectName;
                Session["OfficeNameNep"] = OfficeName.NameNepali;
                Session["local_level_code"] = OfficeName.LocalLevelCode;
                ViewBag.officename = OfficeName.NameNepali;
                return View("~/Views/Frontend/Index.cshtml");
            }
            return RedirectToAction("Index", "Account");

        }
       
        [HttpPost]
        public ActionResult KharidAdesh(FormCollection collection)
        {
            CategoryModel category1 = new CategoryModel();
            category1.Category_name = collection["email"];
           
            category1.Parent_id = 0;
            int letc = category.Insert(category1);

            return View();
        }

        public ActionResult KhadridAdesAddView()
        {
            if (Session["Office_Id"] != null)
            {

                KharidAdeshViewModel Record = new KharidAdeshViewModel();
                KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
                KharidAdesDetailsModel kharidAdeshDetailsModel = new KharidAdesDetailsModel();
                Record.KharidAdeshModel = kharidAdeshModel;
                Record.KharidAdesDetailsModel = kharidAdeshDetailsModel;
                Record.KharidAdeshModel.KharidAdesNumber = kharidAdesObj.getKharidAdeshNumberByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
                Record.CategoryList = categoryObj.GetCategorySelectListItem();
                //Record.ProductList = productObj.GetProductSelectListItem();
                Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
                Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();
                return PartialView("~/Views/Shared/Frontend/KharidAdes/_add.cshtml", Record);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }
/// <summary>
///
/// </summary>
/// <returns></returns>
        public ActionResult KharidAdshEditView()
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            if (Session["Office_Id"] != null)
            {
                List<KharidAdeshModel> kharidAdeshModel = new List<KharidAdeshModel>();
                kharidAdeshModel = kharidAdesObj.getAllKharidAdeshByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
                return PartialView("~/Views/Frontend/_kharidAdshEditView.cshtml", kharidAdeshModel);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }

        public ActionResult KharidAdeshEditViewPage(int id)
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
            KharidAdesDetailsModel KharidAdesDetailsModel = new KharidAdesDetailsModel();
            //Record.KharidAdeshModel = kharidAdeshModel;
            Record.KharidAdesDetailsModel = KharidAdesDetailsModel;
            Record.KharidAdesDetailsModel.kharidAdeshModelList = kharidDetailsObj.getKharidAdeshDetailsByKharidAdeshIdAndOfficeId(id, Convert.ToInt32(Session["Office_Id"].ToString()));

            Session["kharidAdeshId"] = id;

            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            Record.ProductList = productObj.GetProductSelectListItem();
            Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
            Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();
            return PartialView("~/Views/Shared/Frontend/KharidAdes/_kharidAdeshEditPage.cshtml", Record);
        }

        public ActionResult DakhilaAddView()
        {
            DakhilaKharidAdeshViewModel Record = new DakhilaKharidAdeshViewModel();
            DakhilaModel dakhilaModel = new DakhilaModel();
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            if (Session["id"] != null )
            {

                Record.KharidAdeshList = kharidAdesObj.GetKharidListItemsByOfficId(Convert.ToInt32(Session["id"].ToString()));
                //Record.KharidAdeshDetailsList = kharidDetailsObj.GetKharidAdesDetailsList();
                Record.ProductList = productObj.GetProductSelectListItem();
                Record.sellerModelList = sellerObj.GetSellerByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            }
            return PartialView("~/Views/Shared/Frontend/Dakhila/_dakhilaAdd.cshtml",Record);
        }

        public ActionResult MagFaram()
        {

            MagFaramViewModel Record = new MagFaramViewModel();
            MagfaramModel MagfaramModel = new MagfaramModel();
            Record.MagfaramModel = MagfaramModel;
            Record.MagfaramModel.Mag_faram_number = magFaramObj.getMaxMagFaramNumberByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            Record.KarmachariDetailsModel = karmachariDetailsObj.GetKarmachariByOfficeId((Session["Office_Id"].ToString()));
            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            
            Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
            Record.ProductList = productObj.GetProductSelectListItem();
            return PartialView("~/Views/Shared/Frontend/MagFaram/_magFaram.cshtml", Record);
        }

        public ActionResult Nikasa()
        {
            NikasaMagFaramViewModel Record = new NikasaMagFaramViewModel();
            Record.MagFaramList = magFaramObj.GetMagFaramIdByOfficeId(Convert.ToInt32(Session["id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/Nikasa/_nikasaAddView.cshtml",Record);
        }

        public ActionResult KharidAdeshReportView()
        {
            
            KharidAdesDetailsModel Record = new KharidAdesDetailsModel();
            Record.KharidAdeshListItem = kharidAdesObj.GetKharidListItemsByOfficId(Convert.ToInt32(Session["id"].ToString()));
           
            return PartialView("~/Views/Shared/Frontend/KharidAdes/_kharidAdeshReport.cshtml", Record);
        }

       public ActionResult MagFaramReportView()
        {
            MagFaramDetailsModel Record = new MagFaramDetailsModel();
            Record.MagFaramList = magFaramObj.GetMagFaramIdByOfficeId(Convert.ToInt32(Session["id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/MagFaram/_magFaramReport.cshtml", Record);
        }

        public ActionResult KarmachariView()
        {

            return PartialView("~/Views/Shared/Frontend/Karmachari/_karmachari.cshtml");

        }

        public ActionResult SellerView()
        {

            return PartialView("~/Views/Shared/Frontend/Seller/_seller.cshtml");
        }

        public ActionResult FormAuthorityView()
        {
            FormAuthorityModel Record = new FormAuthorityModel();
             Record.KarmachariList = karmachariDetailsObj.getKarmachariDetailsByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/FormAuthority/_formAuthority.cshtml", Record);
        }

        public ActionResult ProductAddView()
        {
            ProductViewModel Record = new ProductViewModel();
            Record.ProductList = productObj.GetAll();
            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            Record.UnitList = unitObj.UnitSelectItem();
            Record.SamanBargaList = samanBargaObj.GetSamanBargaList();
            return PartialView("~/Views/Shared/Frontend/Product/_productAddView.cshtml", Record);
        }

        public ActionResult ProductDetailsAddView()
        {
            ProductDetailsModel Record = new ProductDetailsModel();

IMS/Controllers/KharidAdeshDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.Service.Models;
using IMS.Service.Inteface;
using IMS.Service.Service;
using IMS.Service.ViewModels;

namespace IMS.Controllers
{
    public class KharidAdeshDetailsController : Controller
    {
        // GET: KharidAdeshDetails
        private IKharidAdesDetailsService kharidDetailsObj;
        private ISellerService sellerObj;
        private IDakhilaService dakhilaObj;
        private IDakhilaDetailsService dakhilaDetailsObj;
        private IStoreService storeObj;
        private IOfficeService officeObj;
        public KharidAdeshDetailsController()
        {
            this.kharidDetailsObj = new KharidAdesDetailsService();
            this.sellerObj = new SellerService();
            this.dakhilaObj = new DakhilaService();
            this.dakhilaDetailsObj = new DakhilaDetailsService();
            this.storeObj = new StoreService();
            this.officeObj = new OfficeService();
        }
        public ActionResult Index()
        {
            var KharidAdesDetailsModel = new KharidAdesDetailsModel();
            return View(KharidAdesDetailsModel);
        }

        public JsonResult List(int id)
        {
            List<KharidAdesDetailsModel> data = kharidDetailsObj.GetByKharidAdeshId(id);
            List<SellerModel> sellers = sellerObj.GetSellerByOfficeId1(Convert.ToInt32(Session["id"].ToString()));
            var result = new { Data = data, Sellers = sellers };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult KharidAdesDetailForDakhila(DakhilaDetailsModel [] dakhilaDetails, DakhilaModel dakhila, StoreModel[] store)
        {
           int temp =  dakhilaObj.Insert(dakhila);
            foreach (var item in dakhilaDetails)
            {

                item.dakhila_id = temp;
                dakhilaDetailsObj.Insert(item);
            }
            foreach (var item in store)
            {
                storeObj.Insert(item);
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult KharidAdeshReport(KharidAdesDetailsModel ka)
        {
            OfficeModel OfficeName;
                OfficeName = officeObj.GetOfficeByUser(Convert.ToInt32(Session["id"].ToString()));
                Session["Office_Id"] = OfficeName.Id;
                Session["ProjectName"] = OfficeName.ProjectName;
                Session["OfficeNameNep"] = OfficeName.NameNepali;
            Session["District_Id"] = OfficeName.DistrictId;
            Session["District_name"] = OfficeName.District_Name;
            Session["Local_Level_Type_Name"] = OfficeName.Local_Level_Type_Nmae;
                
               
            
            int khaid_adesh_id = ka.Kharid_ades_id;
            KharidAdeshReportViewModel Record = new KharidAdeshReportViewModel();
            
           List<KharidAdesDetailsModel> kharidAdeshModelList = kharidDetailsObj.GetKharidAdeshDetailsByKharidAdeshId(khaid_adesh_id);
            //Record.DistrictModel =  
            return View(kharidAdeshModelList);
        }
    }
}

IMS/Controllers/NikasaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.Service.Models;
using IMS.Service.Inteface;
using IMS.Service.Service;
using IMS.Service.ViewModels;

namespace IMS.Controllers
{
    public class NikasaController : Controller
    {
        // GET: Nikasa
        private INikasaService nikasaObj;
        private INikasaDetailsService nikasaDetailsObj;
        private IStoreService storeObj;
        public NikasaController()
        {
            this.nikasaObj = new NikasaService();
            this.nikasaDetailsObj = new NikasaDetailsService();
            this.storeObj = new StoreService();
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        public JsonResult SaveFromFront(NikasaModel Nikasa, NikasaDetailsModel[] NikasaDetails, StoreModel[] Store)
        {

            int temp = nikasaObj.Insert(Nikasa);
          

            foreach (var item in NikasaDetails)
            {
                item.Nikasa_Id = temp;
                
                nikasaDetailsObj.Insert(item);
               
            }

            foreach (var item in Store)
            {
                int product_id = item.Product_Id;
                int office_id = item.Office_Id;
                int quantity = item.Quantity;
                storeObj.UpdateProductByOfficeIdProductId(product_id, office_id, quantity);

            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

IMS/Views/Shared/Frontend/Nikasa/_nikasaAddView.cshtml
@model IMS.Service.ViewModels.NikasaMagFaramViewModel
<div class="content-cantainer">
    <div class="opend-file-wrapper">
        <span class="file-icon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
        <span class="opened-file-name">निकासा फारम</span>
    </div>
    <div class="content-field">
        <form class="form-horizontal" id="nikasa_form" method="post" action="@Url.Action("Create", "Nikasa")">

            <div class="form-group">

                @Html.LabelFor(model => model.NikasaModel.Mag_Faram_Id, "माग फारम न.", htmlAttributes: new { @class = "control-label form-label " })

                @Html.DropDownListFor(model => model.NikasaModel.Mag_Faram_Id, Model.MagFaramList,"--माग न. छान्नुहोस--", htmlAttributes: new { @class = "form-field  " })
            </div>

            <div class="form-group">
                <label>मिति</label>
                <input type="text" class="nep_date form-control" id="nepali_date" name="KharidAdeshModel.Created_date" />


            </div>





        </form>
        <form class="form-horizontal" id="dakhilEditProductForm" style="display:none" action="#">
            <div class="form-group">
                <label>Product</label>
                <input type="text" class="form-control product_id_field">
            </div>
            <div class="form-group">
                <label>Kharid Type</label>
                <input type="text" class="form-control kharid_type_id_field">
            </div>
            <div class="form-group">
                <label>quantity</label>
                <input type="text" class="form-control quantity_field">
            </div>
            <div class="form-group">
                @*<div class="form-group">
                        @Html.LabelFor(model => model.DakhilaModel.Kharid_adesh_id, "Seller", htmlAttributes: new { @class = "control-label form-label " })
                        @Html.DropDownListFor(model => model.DakhilaModel.Id, Model.SellerLit, htmlAttributes: new { @class = "form-field  " })
                    </div>*@

            </div>
            <div class="form-control">
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
    <div>


    </div>
    <div class="display-content">
        <table class="table table-bordered " id="nikasa-table">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>माग गर्ने</th>
                    <th>क्याटोगोरी</th>
                    <th>प्रोडक्ट</th>
                    <th>प्रोडक्ट डिटेल्स</th>
                    <th>सङ्ख्या</th>

                </tr>
            </thead>
            <tbody>
                <tr></tr>

            </tbody>
        </table>
        <input type="hidden" id="mag_faram_id" />
        <input type="hidden" value="@Session["id"]" id="myHiddenVar" />
        <input type="hidden" value="@Session["Office_Id"]" id="officeId" />
        <div class="submit-buttonss btn-group">
            <button class="btn btn-primary" id="save" onclick="saveNikasa()" type="button"> Save </button>
            <button class="btn btn-warning" type="button"> Clear </button>
        </div>
    </div>
</div>
<script>
var MyAppUrlSettings = {
    NikasaDetailsURl : '@Url.Action("SaveFromFront", "Nikasa")'
    @*KharidAdesDetailsURL : '@Url.Action("KharidAdesDetailForDakhila", "KharidAdeshDetails")'*@
    }

</script>





    <script>
        $('#NikasaModel_Mag_Faram_Id').change(function () {
            // alert('hunter');
            var id = $(this).val();
            $('#mag_faram_number').val(id);
            var MagFaramNumber = $('#NikasaModel_Mag_Faram_Id').val();

            //console.log(MagFaramNumber);
            var i = 1;
            $.ajax({
                type: "GET",
                url: " Magfaram/GetMagFaramById",
                data: "Id=" + MagFaramNumber,
                success: function (data) {

                    $('#nikasa-table').find('tbody').html('<tr></tr>');

                    $.each(data, function (key, value) {

                        console.log(value);
                        var tr = "<tr id='kharid_adesh_detail" + value.
                            Id + "'>" +
                            "<td>" +
                            i +
                            "</td>" +
                            "<td class='karmachari_id'>" +
                            value.KarmaChari +
                            "</td>" +
                            "<td class='category_id'>" +
                            value.Category_Name +
                            "</td>"+
                            "<td class='product_id'>" +
                            value.Product_Name +
                            "</td>" +
                            "<td class='product_details_id'>" +
                            value.Product_Specification +
                            "</td>" +
                            "<td class='quantity'>" +
                            value.Quantity +
                            "</td>";

                        i = i + 1;
                        //console.log($('#nikasa-table').find('tbody').last('tr').attr('class'))
                        $('#nikasa-table').find('tbody').last('tr').append(tr);
                        //$.each(data.Sellers, function (key1, value1) {
                        //    $('td.seller').last().find('select').append('<option vlaue="' + value1.Id + '">' + value1.Name + '</option>')
                        //});
                    });


                }
            });
        });
    </script>
    <script>
        $('.nep_date').nepaliDatePicker({
            dateFormat: "%y-%m-%d"
        });
        var d = new Date();
        var month = d.getMonth() + 1;
        var day = d.getDate();
        var year = d.getFullYear();
        var nepDate = calendarFunctions.getBsDateByAdDate(year, month, day);
        // console.log(calendarFunctions.getBsDateByAdDate(year, month, day));
        $('#nepali_date').val(calendarFunctions.getNepaliNumber(nepDate.bsYear) + '-' + calendarFunctions.getNepaliNumber(nepDate.bsMonth) + '-' + calendarFunctions.getNepaliNumber(nepDate.bsDate));
    </script>