IMS/Controllers/FrontendController.cs
using IMS.Service.Inteface;
using IMS.Service.Models;
using IMS.Service.Service;
using IMS.Service.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS.Controllers
{
    public class FrontendController : Controller
    {
        private ICategoryService category;

        private IKharidAdesService kharidAdesObj = null;
        private IProductService productObj;
        private IKharidTypeService kharidTypeObj;
        private IKharidAdesDetailsService kharidDetailsObj;
        private ICategoryService categoryObj;
        private IProductDetailsService productDetailsObj;
        private IGoods_exp_type samanBargaObj;
        private ISellerService sellerObj;
        private IOfficeService officeObj;
        private IKarmachariDetailsService karmachariDetailsObj;
        private IMagfaramService magFaramObj;
       
       
        private IUnitService unitObj;

        public FrontendController()
        {
            this.category = new CategoryService();
            productObj = new ProductService();
            kharidAdesObj = new KharidAdesService();
            kharidTypeObj = new KharidTypeService();
            kharidDetailsObj = new KharidAdesDetailsService();
            categoryObj = new CategoryService();
            productDetailsObj = new ProductDetailsService();
            sellerObj = new SellerService();
            officeObj = new OfficeService();
            karmachariDetailsObj = new KarmachariDetailsService();
            magFaramObj = new MagfaramService();
            unitObj = new UnitService();
            samanBargaObj = new GoodExpTypeService();

        }
        // GET: Frontend
        public ActionResult Index()
        {
          
            OfficeModel OfficeName;
           
            if (Session["id"]!= null)
            {

               OfficeName =  officeObj.GetOfficeByUser(Convert.ToInt32(Session["id"].ToString()));
                Session["Office_Id"] = OfficeName.Id;
                Session["ProjectName"] = OfficeName.ProjectName;
                Session["OfficeNameNep"] = OfficeName.NameNepali;
                Session["local_level_code"] = OfficeName.LocalLevelCode;
                ViewBag.officename = OfficeName.NameNepali;
                return View("~/Views/Frontend/Index.cshtml");
            }
            return RedirectToAction("Index", "Account");

        }
       
        [HttpPost]
        public ActionResult KharidAdesh(FormCollection collection)
        {
            CategoryModel category1 = new CategoryModel();
            category1.Category_name = collection["email"];
           
            category1.Parent_id = 0;
            int letc = category.Insert(category1);

            return View();
        }

        public ActionResult KhadridAdesAddView()
        {
            if (Session["Office_Id"] != null)
            {

                KharidAdeshViewModel Record = new KharidAdeshViewModel();
                KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
                KharidAdesDetailsModel kharidAdeshDetailsModel = new KharidAdesDetailsModel();
                Record.KharidAdeshModel = kharidAdeshModel;
                Record.KharidAdesDetailsModel = kharidAdeshDetailsModel;
                Record.KharidAdeshModel.KharidAdesNumber = kharidAdesObj.getKharidAdeshNumberByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
                Record.CategoryList = categoryObj.GetCategorySelectListItem();
                //Record.ProductList = productObj.GetProductSelectListItem();
                Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
                Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();
                return PartialView("~/Views/Shared/Frontend/KharidAdes/_add.cshtml", Record);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }
/// <summary>
///
/// </summary>
/// <returns></returns>
        public ActionResult KharidAdshEditView()
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            if (Session["Office_Id"] != null)
            {
                List<KharidAdeshModel> kharidAdeshModel = new List<KharidAdeshModel>();
                kharidAdeshModel = kharidAdesObj.getAllKharidAdeshByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
                return PartialView("~/Views/Frontend/_kharidAdshEditView.cshtml", kharidAdeshModel);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }

        public ActionResult KharidAdeshEditViewPage(int id)
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
            KharidAdesDetailsModel KharidAdesDetailsModel = new KharidAdesDetailsModel();
            //Record.KharidAdeshModel = kharidAdeshModel;
            Record.KharidAdesDetailsModel = KharidAdesDetailsModel;
            Record.KharidAdesDetailsModel.kharidAdeshModelList = kharidDetailsObj.getKharidAdeshDetailsByKharidAdeshIdAndOfficeId(id, Convert.ToInt32(Session["Office_Id"].ToString()));

            Session["kharidAdeshId"] = id;

            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            Record.ProductList = productObj.GetProductSelectListItem();
            Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
            Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();
            return PartialView("~/Views/Shared/Frontend/KharidAdes/_kharidAdeshEditPage.cshtml", Record);
        }

        public ActionResult DakhilaAddView()
        {
            DakhilaKharidAdeshViewModel Record = new DakhilaKharidAdeshViewModel();
            DakhilaModel dakhilaModel = new DakhilaModel();
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Account");
            }
            if (Session["id"] != null )
            {

                Record.KharidAdeshList = kharidAdesObj.GetKharidListItemsByOfficId(Convert.ToInt32(Session["id"].ToString()));
                //Record.KharidAdeshDetailsList = kharidDetailsObj.GetKharidAdesDetailsList();
                Record.ProductList = productObj.GetProductSelectListItem();
                Record.sellerModelList = sellerObj.GetSellerByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            }
            return PartialView("~/Views/Shared/Frontend/Dakhila/_dakhilaAdd.cshtml",Record);
        }

        public ActionResult MagFaram()
        {

            MagFaramViewModel Record = new MagFaramViewModel();
            MagfaramModel MagfaramModel = new MagfaramModel();
            Record.MagfaramModel = MagfaramModel;
            Record.MagfaramModel.Mag_faram_number = magFaramObj.getMaxMagFaramNumberByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            Record.KarmachariDetailsModel = karmachariDetailsObj.GetKarmachariByOfficeId((Session["Office_Id"].ToString()));
            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            
            Record.ProductDetailsList = productDetailsObj.GetProductDetailsList();
            Record.ProductList = productObj.GetProductSelectListItem();
            return PartialView("~/Views/Shared/Frontend/MagFaram/_magFaram.cshtml", Record);
        }

        public ActionResult Nikasa()
        {
            NikasaMagFaramViewModel Record = new NikasaMagFaramViewModel();
            Record.MagFaramList = magFaramObj.GetMagFaramIdByOfficeId(Convert.ToInt32(Session["id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/Nikasa/_nikasaAddView.cshtml",Record);
        }

        public ActionResult KharidAdeshReportView()
        {
            
            KharidAdesDetailsModel Record = new KharidAdesDetailsModel();
            Record.KharidAdeshListItem = kharidAdesObj.GetKharidListItemsByOfficId(Convert.ToInt32(Session["id"].ToString()));
           
            return PartialView("~/Views/Shared/Frontend/KharidAdes/_kharidAdeshReport.cshtml", Record);
        }

       public ActionResult MagFaramReportView()
        {
            MagFaramDetailsModel Record = new MagFaramDetailsModel();
            Record.MagFaramList = magFaramObj.GetMagFaramIdByOfficeId(Convert.ToInt32(Session["id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/MagFaram/_magFaramReport.cshtml", Record);
        }

        public ActionResult KarmachariView()
        {

            return PartialView("~/Views/Shared/Frontend/Karmachari/_karmachari.cshtml");

        }

        public ActionResult SellerView()
        {

            return PartialView("~/Views/Shared/Frontend/Seller/_seller.cshtml");
        }

        public ActionResult FormAuthorityView()
        {
            FormAuthorityModel Record = new FormAuthorityModel();
             Record.KarmachariList = karmachariDetailsObj.getKarmachariDetailsByOfficeId(Convert.ToInt32(Session["Office_Id"].ToString()));
            return PartialView("~/Views/Shared/Frontend/FormAuthority/_formAuthority.cshtml", Record);
        }

        public ActionResult ProductAddView()
        {
            ProductViewModel Record = new ProductViewModel();
            Record.ProductList = productObj.GetAll();
            Record.CategoryList = categoryObj.GetCategorySelectListItem();
            Record.UnitList = unitObj.UnitSelectItem();
            Record.SamanBargaList = samanBargaObj.GetSamanBargaList();
            return PartialView("~/Views/Shared/Frontend/Product/_productAddView.cshtml", Record);
        }

        public ActionResult ProductDetailsAddView()
        {
            ProductDetailsModel Record = new ProductDetailsModel();

IMS/Controllers/KharidAdesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.Service.Inteface;
using IMS.Service.Service;
using IMS.Service.Models;
using IMS.Repository.Entities;
using IMS.Service.ViewModels;

namespace IMS.Controllers
{
    public class KharidAdesController : Controller
    {
        // GET: KharidAdes
        private IKharidAdesService kharidAdesObj = null;
        private IProductService productObj;
        private IKharidTypeService kharidTypeObj;
        private IKharidAdesDetailsService kharidDetailsObj;
        private IStoreService storeObj;
        public KharidAdesController()
        {
            productObj = new ProductService();
            kharidAdesObj = new KharidAdesService();
            kharidTypeObj = new KharidTypeService();
            kharidDetailsObj = new KharidAdesDetailsService();
            storeObj = new StoreService();
                
                }
        public ActionResult Index()
        {
           // ViewBag.modelRecord = kharidAdesObj.GetAll();
           
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            //KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
           
            //Record.KharidAdeshModel = kharidAdeshModel;
            Record.KharidAdeshList = kharidAdesObj.GetKharidListItem();
            return View(Record);
        }

        [HttpGet]
        public ActionResult Create()
        {
            KharidAdeshViewModel Record = new KharidAdeshViewModel();
            KharidAdeshModel kharidAdeshModel = new KharidAdeshModel();
            KharidAdesDetailsModel kharidAdeshDetailsModel = new KharidAdesDetailsModel();
            Record.KharidAdeshModel = kharidAdeshModel;
            Record.KharidAdesDetailsModel = kharidAdeshDetailsModel;
            Record.ProductList = productObj.GetProductSelectListItem();
            Record.KharidPrakarList = kharidTypeObj.GetKharidPrakarSelectListItem();


            return View(Record);
        }

        [HttpPost]
        public ActionResult Create(KharidAdeshViewModel km)
        {
            
            var kharidAdesh = new KharidAdeshModel()
            {
                KharidAdesNumber = km.KharidAdeshModel.KharidAdesNumber,
                CreatedDate = km.KharidAdeshModel.CreatedDate,
                Status = 1,
                Office_id = "1"
            };
            kharidAdesObj.Insert(kharidAdesh);

            var kharidAdesDetails = new KharidAdesDetailsModel()
            {
                Kharid_ades_id = km.KharidAdeshModel.KharidAdesNumber,
                Product_id = km.KharidAdeshModel.product_id,
                Kharid_type_id = km.KharidAdesDetailsModel.Kharid_type_id,
                Quantity = km.KharidAdesDetailsModel.Quantity,

            };


            kharidDetailsObj.Insert(kharidAdesDetails);

            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.productList = productObj.GetAllProduct();
            ViewBag.modelRecord = kharidAdesObj.GetAllKharidAdes().Find(p => p.Id.Equals(id));
            return View();
        }

        [HttpPost]
        public ActionResult Edit(KharidAdeshModel km)
        {
            kharidAdesObj.Update(km);
            kharidAdesObj.Save();
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id)
        {
            kharidAdesObj.Delete(id);
            kharidAdesObj.Save();
            return RedirectToAction("Index");
        }



        public JsonResult SaveFromFront(KharidAdeshModel KharidAdes, KharidAdesDetailsModel [] KharidAdesDetails)
        {
            
           int temp = kharidAdesObj.Insert(KharidAdes);   
             
            foreach (var item in KharidAdesDetails)
            {
               item.Kharid_ades_id = temp;
             
                kharidDetailsObj.Insert(item);
            }
           
            
            return Json(true, JsonRequestBehavior.AllowGet);
        }

       
    }
}

IMS/Controllers/KharidAdeshDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IMS.Service.Models;
using IMS.Service.Inteface;
using IMS.Service.Service;
using IMS.Service.ViewModels;

namespace IMS.Controllers
{
    public class KharidAdeshDetailsController : Controller
    {
        // GET: KharidAdeshDetails
        private IKharidAdesDetailsService kharidDetailsObj;
        private ISellerService sellerObj;
        private IDakhilaService dakhilaObj;
        private IDakhilaDetailsService dakhilaDetailsObj;
        private IStoreService storeObj;
        private IOfficeService officeObj;
        public KharidAdeshDetailsController()
        {
            this.kharidDetailsObj = new KharidAdesDetailsService();
            this.sellerObj = new SellerService();
            this.dakhilaObj = new DakhilaService();
            this.dakhilaDetailsObj = new DakhilaDetailsService();
            this.storeObj = new StoreService();
            this.officeObj = new OfficeService();
        }
        public ActionResult Index()
        {
            var KharidAdesDetailsModel = new KharidAdesDetailsModel();
            return View(KharidAdesDetailsModel);
        }

        public JsonResult List(int id)
        {
            List<KharidAdesDetailsModel> data = kharidDetailsObj.GetByKharidAdeshId(id);
            List<SellerModel> sellers = sellerObj.GetSellerByOfficeId1(Convert.ToInt32(Session["id"].ToString()));
            var result = new { Data = data, Sellers = sellers };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult KharidAdesDetailForDakhila(DakhilaDetailsModel [] dakhilaDetails, DakhilaModel dakhila, StoreModel[] store)
        {
           int temp =  dakhilaObj.Insert(dakhila);
            foreach (var item in dakhilaDetails)
            {

                item.dakhila_id = temp;
                dakhilaDetailsObj.Insert(item);
            }
            foreach (var item in store)
            {
                storeObj.Insert(item);
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult KharidAdeshReport(KharidAdesDetailsModel ka)
        {
            OfficeModel OfficeName;
                OfficeName = officeObj.GetOfficeByUser(Convert.ToInt32(Session["id"].ToString()));
                Session["Office_Id"] = OfficeName.Id;
                Session["ProjectName"] = OfficeName.ProjectName;
                Session["OfficeNameNep"] = OfficeName.NameNepali;
            Session["District_Id"] = OfficeName.DistrictId;
            Session["District_name"] = OfficeName.District_Name;
            Session["Local_Level_Type_Name"] = OfficeName.Local_Level_Type_Nmae;
                
               
            
            int khaid_adesh_id = ka.Kharid_ades_id;
            KharidAdeshReportViewModel Record = new KharidAdeshReportViewModel();
            
           List<KharidAdesDetailsModel> kharidAdeshModelList = kharidDetailsObj.GetKharidAdeshDetailsByKharidAdeshId(khaid_adesh_id);
            //Record.DistrictModel =  
            return View(kharidAdeshModelList);
        }
    }
}

IMS/Views/Shared/Frontend/KharidAdes/_add.cshtml
@model IMS.Service.ViewModels.KharidAdeshViewModel
<div class="content-cantainer">
    <div class="opend-file-wrapper">
        <span class="file-icon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
        <span class="opened-file-name">खरिद आदेश</span>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="content-field">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <form class="form-horizontal" id="kharid_ades_form" method="post" action="@Url.Action("Create", "KharidAdes")">
                <div class="form-group">
                    <label class="control-label form-label">मिति</label>
                    <input type="text" class="nep_date form-control form-field" id="nepali_date" name="KharidAdeshModel.Created_date" />
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.KharidAdeshModel.KharidAdesNumber, "खरिद आदेश न.", htmlAttributes: new { @class = "control-label form-label" })
                    @Html.EditorFor(model => model.KharidAdeshModel.KharidAdesNumber, new { htmlAttributes = new { disabled = "disabled", @class = "form-field" } })
                    @Html.ValidationMessageFor(model => model.KharidAdeshModel.KharidAdesNumber, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KharidAdeshModel.Category_Id, "क्याटेगोरी", htmlAttributes: new { @class = "control-label form-label " })
                    @Html.DropDownListFor(model => model.KharidAdeshModel.Category_Id, Model.CategoryList, "---------", htmlAttributes: new { @class = "form-field category" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KharidAdeshModel.product_id, "प्रोडक्ट", htmlAttributes: new { @class = "control-label form-label product" })

                    @Html.DropDownListFor(model => model.ProductModel.Id, new SelectList(" "), "----------", new { @class = "form-field product" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ProductDetailsModel.Id, "प्रोडक्ट डिटेल्स", htmlAttributes: new { @class = "control-label form-label" })
                    @Html.DropDownListFor(model => model.ProductDetailsModel.Id, new SelectList(" "), "----------", new { @class = "form-field product_details" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KharidAdesDetailsModel.Kharid_type_id, "खरिद किसिम", htmlAttributes: new { @class = "form-label control-label" })
                    @Html.DropDownListFor(model => model.KharidAdesDetailsModel.Kharid_type_id, Model.KharidPrakarList, "--खरिद किसिम छान्नुहोस--", htmlAttributes: new { @class = "form-field kharid_type" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.KharidAdesDetailsModel.Quantity, "क्वान्टिटी", htmlAttributes: new { @class = "form-label control-label" })
                    @Html.EditorFor(model => model.KharidAdesDetailsModel.Quantity, new { htmlAttributes = new { @class = "form-field quantity" } })
                    @Html.ValidationMessageFor(model => model.KharidAdesDetailsModel.Quantity, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" id="kharid_ades_form_btn" onclick="KharidAdeshFormSubmit(event)" class="btn btn-primary form-field">थप</button>
                    </div>
                </div>
            </form>
        </div>
    }
    <div class="display-content">
        <table class="table table-bordered " id="kharid_ades_table">
            <thead>
                <tr>
                    <th>सि न.</th>
                    <th>क्याटोगोरी</th>
                    <th>प्रोडक्ट</th>
                    <th>प्रोडक्ट डिटेल्स</th>
                    <th>खरिद किसिम</th>
                    <th>क्वान्टिटी</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <tr></tr>

            </tbody>
        </table>
        <input type="hidden" class="nep_date1 form-control" id="nepali_month" name="KharidAdeshModel.Created_date" />
        <input type="hidden" value="@Session["id"]" id="myHiddenVar" />
        <input type="hidden" value="@Session["Office_Id"]" id="officeId" />
        <div class="submit-buttonss btn-group">
            <button class="btn btn-primary" id="save" onclick="save()" type="button"> Save </button>
            <button class="btn btn-warning" type="button"> Clear </button>
        </div>
    </div>
</div>

<div id="ndp-nepali-box" class="ndp-corner-all" style="display:none"><span id="ndp-target-id" style="display:none"></span><div class="ndp-corner-all ndp-header"><a href="javascript:void(0)" id="prev" title="Previous Month" class="ndp-prev"></a><a href="javascript:void(0)" id="next" title="Next Month" class="ndp-next"></a><span id="currentMonth"></span></div><table><tbody><tr class="ndp-days"><th>आ</th><th>सो</th><th>मं</th><th>बु</th><th>बि</th><th>शु</th><th>श</th></tr></tbody></table></div>
<script>
var MyAppUrlSettings = {
    KharidAdesURL : '@Url.Action("SaveFromFront","KharidAdes")'  // ("Function" ,"Controller")
}
</script>
<script>
    $('.nep_date').nepaliDatePicker({
        dateFormat: "%y-%m-%d"
    });
    var d = new Date();
    var month = d.getMonth() + 1;
    var day = d.getDate();
    var year = d.getFullYear();
    var nepDate = calendarFunctions.getBsDateByAdDate(year, month, day);
    // console.log(calendarFunctions.getBsDateByAdDate(year, month, day));
    $('#nepali_date').val((nepDate.bsYear) + '-' + (nepDate.bsMonth) + '-' + (nepDate.bsDate));
</script>
<script>
    $('.nep_date1').nepaliDatePicker({
        dateFormat: "%y-%m-%d"
    });
    var d = new Date();
    var month = d.getMonth() + 1;
    var day = d.getDate();
    var year = d.getFullYear();
    var nepDate = calendarFunctions.getBsDateByAdDate(year, month, day);
    // console.log(calendarFunctions.getBsDateByAdDate(year, month, day));
    $('#nepali_month').val((nepDate.bsMonth));
</script>

<script>
    $(document).ready(function () {
        $('#KharidAdeshModel_Category_Id').change(function () {
            var category_id = $(this).val();
            var office_id = $('#officeId').val();
            //alert('hunter');
            //console.log(category_id);
            //console.log(office_id);
            $.ajax({

                url: "/Product/GetProductByCategoryIdOfficeId/",
                data: {
                    category_id: category_id,
                    office_id: office_id
                },
                type: 'Get',
                contentType: "json",
                dataType: "json",
                success: function (result) {
                    $("#ProductModel_Id").html(' '); //khali gareko

                    $("#ProductModel_Id").append("<option>---------</option>")

                    $.each(result, function (key, value) {
                        //console.log(value);
                        $("#ProductModel_Id").append("<option value='" + value.Id + "'>" + value.Product_name + "</option>")
                    })
                }

            })
        });

    });

</script>

<script>
    $(document).ready(function () {
        $('#ProductModel_Id').change(function () {
            var product_id = $('#ProductModel_Id').val();
            var office_id = $('#officeId').val();
            //alert('hunter');
            $.ajax({
                url: "/ProductDetails/getProductDetailsByProductId/",
                data: {
                    product_id: product_id,
                    office_id: office_id
                },

                type: 'Get',
                contentType: JSON,
                success: function (result) {

                    $("#ProductDetailsModel_Id").html(' ');
                    $("#ProductDetailsModel_Id").append("<option>-------- </option>")

                    $.each(result, function (key, value) {
                        //console.log(value);
                        $("#ProductDetailsModel_Id").append("<option value='" + value.Id + "'>" + value.Specification_Name + "</option>")
                    })
                }
            })
        });

    });
</script>

<script>
    function getData() {
        //alert('hunter');
       
       
        var category_id = $(event.target).parent().parent().find('.category_id').text();   // from Application.js line 48
        var product_id = $(event.target).parent().parent().find('.product_id').text();
        var product_details_id = $(event.target).parent().parent().find('.product_details_id').text();
        var kharid_type_id = $(event.target).parent().parent().find('.kharid_type_id').text();
        var quantity = $(event.target).parent().parent().find('.quantity').text();
        $('#kharid_ades_form').find('#KharidAdeshModel_Category_Id').val(category_id);
        //$('#kharid_ades_form').find('.form-field product').val(product_id);
        //$('#kharid_ades_form').find('.form-field product_details').val(product_details_id);
        //$('#kharid_ades_form').find('.form-field kharid_type').val(kharid_type_id);
        //$('#kharid_ades_form').find('.form-field quantity text-box single-line').val(quantity);
        console.log($(event.target).parent().parent().find('.category_id').text());
        console.log($(event.target).parent().parent().find('.product_id').text());
    }
</script>

IMS/Views/Shared/Frontend/KharidAdes/_kharidAdeshEdit.cshtml
@model List<IMS.Service.Models.KharidAdeshModel>

<div class="content-cantainer">
    <div class="opend-file-wrapper">
        <span class="file-icon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
        <span class="opened-file-name">खरिद आदेश संसोधन फारम</span>
    </div>
    <table class="table">
        <tr>
            <th>
                SN
            </th>
            <th> खरिद आदेश न.</th>


            <th>
                मिति
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.KharidAdesNumber)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>


                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

IMS/Views/Shared/Frontend/KharidAdes/_kharidAdeshReport.cshtml
@model IMS.Service.Models.KharidAdesDetailsModel

@using (Html.BeginForm("KharidAdeshReport", "KharidAdeshDetails",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Khrid Adesh Report</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="miti">आर्थिक वर्ष</label>
            <select>
               
                <option>2075/76</option>
            </select>
        </div>
        <div class="form-group">
           
            <div class="col-md-10">

                @Html.LabelFor(model => model.Kharid_ades_id, "खरिद आदेश न.", htmlAttributes: new { @class = "control-label form-label " })

                @Html.DropDownListFor(model => model.Kharid_ades_id, Model.KharidAdeshListItem, "--खरिद आदेश न. छान्नुहोस--",htmlAttributes: new { @class = "form-field  " })
            </div>
        </div>

     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" formtarget="_blank" value="हेर्ने" class="btn btn-default" />
            </div>
        </div>
    </div>
}